export default [
{"root":"C","name":"major","notes":"C E G","common":true,"symbols":["","M"]},
{"root":"C#","name":"major","notes":"C# F G#","symbols":["","M"]},
{"root":"D","name":"major","notes":"D F# A","common":true,"symbols":["","M"]},
{"root":"Eb","name":"major","notes":"Eb G Bb","symbols":["","M"]},
{"root":"E","name":"major","notes":"E G# B","common":true,"symbols":["","M"]},
{"root":"F","name":"major","notes":"F A C","common":true,"symbols":["","M"]},
{"root":"F#","name":"major","notes":"F# A# C#","symbols":["","M"]},
{"root":"G","name":"major","notes":"G B D","common":true,"symbols":["","M"]},
{"root":"Ab","name":"major","notes":"Ab C Eb","symbols":["","M"]},
{"root":"A","name":"major","notes":"A C# E","common":true,"symbols":["","M"]},
{"root":"Bb","name":"major","notes":"Bb D F","symbols":["","M"]},
{"root":"B","name":"major","notes":"B D# F#","symbols":["","M"]},
{"root":"C","name":"minor","notes":"C Eb G","symbols":["m", " minor"]},
{"root":"C#","name":"minor","notes":"C# E G#","symbols":["m", " minor"]},
{"root":"D","name":"minor","notes":"D F A","common":true,"symbols":["m", " minor"]},
{"root":"Eb","name":"minor","notes":"Eb Gb Bb","symbols":["m", " minor"]},
{"root":"E","name":"minor","notes":"E G B","common":true,"symbols":["m", " minor"]},
{"root":"F","name":"minor","notes":"F Ab C","symbols":["m", " minor"]},
{"root":"F#","name":"minor","notes":"F# A C#","symbols":["m", " minor"]},
{"root":"G","name":"minor","notes":"G Bb D","symbols":["m", " minor"]},
{"root":"Ab","name":"minor","notes":"Ab B Eb","symbols":["m", " minor"]},
{"root":"A","name":"minor","notes":"A C E","common":true,"symbols":["m", " minor"]},
{"root":"Bb","name":"minor","notes":"Bb Db F","symbols":["m", " minor"]},
{"root":"B","name":"minor","notes":"B D F#","symbols":["m", " minor"]},
{"root":"C","name":"diminished","notes":"C Eb Gb","symbols":["°"," diminished"]},
{"root":"C#","name":"diminished","notes":"C# E G","symbols":["°"," diminished"]},
{"root":"D","name":"diminished","notes":"D F Ab","symbols":["°"," diminished"]},
{"root":"Eb","name":"diminished","notes":"Eb Gb A","symbols":["°"," diminished"]},
{"root":"E","name":"diminished","notes":"E G Bb","symbols":["°"," diminished"]},
{"root":"F","name":"diminished","notes":"F Ab B","symbols":["°"," diminished"]},
{"root":"F#","name":"diminished","notes":"F# A C","symbols":["°"," diminished"]},
{"root":"G","name":"diminished","notes":"G Bb Db","symbols":["°"," diminished"]},
{"root":"Ab","name":"diminished","notes":"Ab B D","symbols":["°"," diminished"]},
{"root":"A","name":"diminished","notes":"A C Eb","symbols":["°"," diminished"]},
{"root":"Bb","name":"diminished","notes":"Bb Db E","symbols":["°"," diminished"]},
{"root":"B","name":"diminished","notes":"B D F","symbols":["°"," diminished"]},
{"root":"C","name":"diminished seventh","notes":"C Eb Gb A","symbols":["°7"," diminished seventh"]},
{"root":"C#","name":"diminished seventh","notes":"C# E G Bb","symbols":["°7"," diminished seventh"]},
{"root":"D","name":"diminished seventh","notes":"D F Ab B","symbols":["°7"," diminished seventh"]},
{"root":"Eb","name":"diminished seventh","notes":"Eb Gb A Dbb C","symbols":["°7"," diminished seventh"]},
{"root":"E","name":"diminished seventh","notes":"E G Bb Db","symbols":["°7"," diminished seventh"]},
{"root":"F","name":"diminished seventh","notes":"F Ab B D","symbols":["°7"," diminished seventh"]},
{"root":"F#","name":"diminished seventh","notes":"F# A C Eb","symbols":["°7"," diminished seventh"]},
{"root":"G","name":"diminished seventh","notes":"G Bb Db E","symbols":["°7"," diminished seventh"]},
{"root":"Ab","name":"diminished seventh","notes":"Ab B D F","symbols":["°7"," diminished seventh"]},
{"root":"A","name":"diminished seventh","notes":"A C Eb Gb","symbols":["°7"," diminished seventh"]},
{"root":"Bb","name":"diminished seventh","notes":"Bb Db E G","symbols":["°7"," diminished seventh"]},
{"root":"B","name":"diminished seventh","notes":"B D F Ab","symbols":["°7"," diminished seventh"]},
{"root":"C","name":"augmented","notes":"C E G#","symbols":["+"," augmented"]},
{"root":"C#","name":"augmented","notes":"C# F A","symbols":["+"," augmented"]},
{"root":"D","name":"augmented","notes":"D F# A#","symbols":["+"," augmented"]},
{"root":"Eb","name":"augmented","notes":"Eb G B","symbols":["+"," augmented"]},
{"root":"E","name":"augmented","notes":"E G# C","symbols":["+"," augmented"]},
{"root":"F","name":"augmented","notes":"F A C#","symbols":["+"," augmented"]},
{"root":"F#","name":"augmented","notes":"F# A# D","symbols":["+"," augmented"]},
{"root":"G","name":"augmented","notes":"G B D#","symbols":["+"," augmented"]},
{"root":"Ab","name":"augmented","notes":"Ab C E","symbols":["+"," augmented"]},
{"root":"A","name":"augmented","notes":"A C# F","symbols":["+"," augmented"]},
{"root":"Bb","name":"augmented","notes":"Bb D F#","symbols":["+"," augmented"]},
{"root":"B","name":"augmented","notes":"B D# G","symbols":["+"," augmented"]},
{"root":"C","name":"dominant seventh","notes":"C E G Bb","common":true,"symbols":["7", "dom7"]},
{"root":"C#","name":"dominant seventh","notes":"C# F G# B","symbols":["7", "dom7"]},
{"root":"D","name":"dominant seventh","notes":"D F# A C","common":true,"symbols":["7", "dom7"]},
{"root":"Eb","name":"dominant seventh","notes":"Eb G Bb Db","symbols":["7", "dom7"]},
{"root":"E","name":"dominant seventh","notes":"E G# B D","common":true,"symbols":["7", "dom7"]},
{"root":"F","name":"dominant seventh","notes":"F A C Eb","symbols":["7", "dom7"]},
{"root":"F#","name":"dominant seventh","notes":"F# A# C# E","symbols":["7", "dom7"]},
{"root":"G","name":"dominant seventh","notes":"G B D F","common":true,"symbols":["7", "dom7"]},
{"root":"Ab","name":"dominant seventh","notes":"Ab C Eb Gb","symbols":["7", "dom7"]},
{"root":"A","name":"dominant seventh","notes":"A C# E G","common":true,"symbols":["7", "dom7"]},
{"root":"Bb","name":"dominant seventh","notes":"Bb D F Ab","symbols":["7", "dom7"]},
{"root":"B","name":"dominant seventh","notes":"B D# F# A","common":true,"symbols":["7", "dom7"]},
{"root":"C","name":"minor seventh","notes":"C Eb G Bb","symbols":["m7","min7"]},
{"root":"C#","name":"minor seventh","notes":"C# E G# B","symbols":["m7","min7"]},
{"root":"D","name":"minor seventh","notes":"D F A C","common":true,"symbols":["m7","min7"]},
{"root":"Eb","name":"minor seventh","notes":"Eb Gb Bb Db","symbols":["m7","min7"]},
{"root":"E","name":"minor seventh","notes":"E G B D","symbols":["m7","min7"]},
{"root":"F","name":"minor seventh","notes":"F Ab C Eb","symbols":["m7","min7"]},
{"root":"F#","name":"minor seventh","notes":"F# A C# E","symbols":["m7","min7"]},
{"root":"G","name":"minor seventh","notes":"G Bb D F","symbols":["m7","min7"]},
{"root":"Ab","name":"minor seventh","notes":"Ab B Eb Gb","symbols":["m7","min7"]},
{"root":"A","name":"minor seventh","notes":"A C E G","common":true,"symbols":["m7","min7"]},
{"root":"Bb","name":"minor seventh","notes":"Bb Db F Ab","symbols":["m7","min7"]},
{"root":"B","name":"minor seventh","notes":"B D F# A","symbols":["m7","min7"]},
{"root":"C","name":"major seventh","notes":"C E G B","common":true,"symbols":["Maj7" ," M7", "M7"]},
{"root":"C#","name":"major seventh","notes":"C# F G# C","symbols":["Maj7" ," M7", "M7"]},
{"root":"D","name":"major seventh","notes":"D F# A C#","symbols":["Maj7" ," M7", "M7"]},
{"root":"Eb","name":"major seventh","notes":"Eb G Bb D","symbols":["Maj7" ," M7", "M7"]},
{"root":"E","name":"major seventh","notes":"E G# B D#","symbols":["Maj7" ," M7", "M7"]},
{"root":"F","name":"major seventh","notes":"F A C E","common":true,"symbols":["Maj7" ," M7", "M7"]},
{"root":"F#","name":"major seventh","notes":"F# A# C# F","symbols":["Maj7" ," M7", "M7"]},
{"root":"G","name":"major seventh","notes":"G B D F#","symbols":["Maj7" ," M7", "M7"]},
{"root":"Ab","name":"major seventh","notes":"Ab C Eb G","symbols":["Maj7" ," M7", "M7"]},
{"root":"A","name":"major seventh","notes":"A C# E G#","common":true,"symbols":["Maj7" ," M7", "M7"]},
{"root":"Bb","name":"major seventh","notes":"Bb D F A","symbols":["Maj7" ," M7", "M7"]},
{"root":"B","name":"major seventh","notes":"B D# F# A#","symbols":["Maj7" ," M7", "M7"]},
{"root":"C","name":"major sixth","notes":"C E G A","symbols":["M6","6."]},
{"root":"C#","name":"major sixth","notes":"C# F G# A#","symbols":["M6","6."]},
{"root":"D","name":"major sixth","notes":"D F# A B","symbols":["M6","6."]},
{"root":"Eb","name":"major sixth","notes":"Eb G Bb C","symbols":["M6","6."]},
{"root":"E","name":"major sixth","notes":"E G# B C#","symbols":["M6","6."]},
{"root":"F","name":"major sixth","notes":"F A C D","symbols":["M6","6."]},
{"root":"F#","name":"major sixth","notes":"F# A# C# D#","symbols":["M6","6."]},
{"root":"G","name":"major sixth","notes":"G B D E","symbols":["M6","6."]},
{"root":"Ab","name":"major sixth","notes":"Ab C Eb F","symbols":["M6","6."]},
{"root":"A","name":"major sixth","notes":"A C# E F#","symbols":["M6","6."]},
{"root":"Bb","name":"major sixth","notes":"Bb D F G","symbols":["M6","6."]},
{"root":"B","name":"major sixth","notes":"B D# F# G#","symbols":["M6","6."]},
{"root":"C","name":"minor sixth","notes":"C Eb G A","symbols":["M6","6."]},
{"root":"C#","name":"minor sixth","notes":"C# E G# A#","symbols":["m6", " minor 6"]},
{"root":"D","name":"minor sixth","notes":"D F A B","symbols":["m6", " minor 6"]},
{"root":"Eb","name":"minor sixth","notes":"Eb Gb Bb C","symbols":["m6", " minor 6"]},
{"root":"E","name":"minor sixth","notes":"E G B C#","symbols":["m6", " minor 6"]},
{"root":"F","name":"minor sixth","notes":"F Ab C D","symbols":["m6", " minor 6"]},
{"root":"F#","name":"minor sixth","notes":"F# A C# D#","symbols":["m6", " minor 6"]},
{"root":"G","name":"minor sixth","notes":"G Bb D E","symbols":["m6", " minor 6"]},
{"root":"Ab","name":"minor sixth","notes":"Ab B Eb F","symbols":["m6", " minor 6"]},
{"root":"A","name":"minor sixth","notes":"A C E F#","symbols":["m6", " minor 6"]},
{"root":"Bb","name":"minor sixth","notes":"Bb Db F G","symbols":["m6", " minor 6"]},
{"root":"B","name":"minor sixth","notes":"B D F# G#","symbols":["m6", " minor 6"]},
{"root":"C","name":"seventh sharp five","notes":"C E G# Bb","symbols":["7+5","7#5"]},
{"root":"C#","name":"seventh sharp five","notes":"C# F A B","symbols":["7+5","7#5"]},
{"root":"D","name":"seventh sharp five","notes":"D F# A# C","symbols":["7+5","7#5"]},
{"root":"Eb","name":"seventh sharp five","notes":"Eb G B Db","symbols":["7+5","7#5"]},
{"root":"E","name":"seventh sharp five","notes":"E G# C D","symbols":["7+5","7#5"]},
{"root":"F","name":"seventh sharp five","notes":"F A C# Eb","symbols":["7+5","7#5"]},
{"root":"F#","name":"seventh sharp five","notes":"F# A# D E","symbols":["7+5","7#5"]},
{"root":"G","name":"seventh sharp five","notes":"G B D# F","symbols":["7+5","7#5"]},
{"root":"Ab","name":"seventh sharp five","notes":"Ab C E Gb","symbols":["7+5","7#5"]},
{"root":"A","name":"seventh sharp five","notes":"A C# F G","symbols":["7+5","7#5"]},
{"root":"Bb","name":"seventh sharp five","notes":"Bb D F# Ab","symbols":["7+5","7#5"]},
{"root":"B","name":"seventh sharp five","notes":"B D# G A","symbols":["7+5","7#5"]},
{"root":"C","name":"seventh flat five","notes":"C E Gb Bb","symbols":["7b5","7♭5"]},
{"root":"C#","name":"seventh flat five","notes":"C# F G B","symbols":["7b5","7♭5"]},
{"root":"D","name":"seventh flat five","notes":"D F# Ab C","symbols":["7b5","7♭5"]},
{"root":"Eb","name":"seventh flat five","notes":"Eb G A Db","symbols":["7b5","7♭5"]},
{"root":"E","name":"seventh flat five","notes":"E G# Bb D","symbols":["7b5","7♭5"]},
{"root":"F","name":"seventh flat five","notes":"F A B Eb","symbols":["7b5","7♭5"]},
{"root":"F#","name":"seventh flat five","notes":"F# A# C E","symbols":["7b5","7♭5"]},
{"root":"G","name":"seventh flat five","notes":"G B Db F","symbols":["7b5","7♭5"]},
{"root":"Ab","name":"seventh flat five","notes":"Ab C D Gb","symbols":["7b5","7♭5"]},
{"root":"A","name":"seventh flat five","notes":"A C# Eb G","symbols":["7b5","7♭5"]},
{"root":"Bb","name":"seventh flat five","notes":"Bb D E Ab","symbols":["7b5","7♭5"]},
{"root":"B","name":"seventh flat five","notes":"B D# F A","symbols":["7b5","7♭5"]},
{"root":"C","name":"major seventh flat third","notes":"C Eb G B","symbols":["M7b3","Δ7♭3"]},
{"root":"C#","name":"major seventh flat third","notes":"C# E G# C","symbols":["M7b3","Δ7♭3"]},
{"root":"D","name":"major seventh flat third","notes":"D F A C#","symbols":["M7b3","Δ7♭3"]},
{"root":"Eb","name":"major seventh flat third","notes":"Eb Gb Bb D","symbols":["M7b3","Δ7♭3"]},
{"root":"E","name":"major seventh flat third","notes":"E G B D#","symbols":["M7b3","Δ7♭3"]},
{"root":"F","name":"major seventh flat third","notes":"F Ab C E","symbols":["M7b3","Δ7♭3"]},
{"root":"F#","name":"major seventh flat third","notes":"F# A C# F","symbols":["M7b3","Δ7♭3"]},
{"root":"G","name":"major seventh flat third","notes":"G Bb D F#","symbols":["M7b3","Δ7♭3"]},
{"root":"Ab","name":"major seventh flat third","notes":"Ab B Eb G","symbols":["M7b3","Δ7♭3"]},
{"root":"A","name":"major seventh flat third","notes":"A C E G#","symbols":["M7b3","Δ7♭3"]},
{"root":"Bb","name":"major seventh flat third","notes":"Bb Db F A","symbols":["M7b3","Δ7♭3"]},
{"root":"B","name":"major seventh flat third","notes":"B D F# A#","symbols":["M7b3","Δ7♭3"]},
{"root":"C","name":"minor seventh flat five","notes":"C Eb Gb Bb","symbols":["m7b5","ø7"]},
{"root":"C#","name":"minor seventh flat five","notes":"C# E G B","symbols":["m7b5","ø7"]},
{"root":"D","name":"minor seventh flat five","notes":"D F Ab C","symbols":["m7b5","ø7"]},
{"root":"Eb","name":"minor seventh flat five","notes":"Eb Gb A Db","symbols":["m7b5","ø7"]},
{"root":"E","name":"minor seventh flat five","notes":"E G Bb D","symbols":["m7b5","ø7"]},
{"root":"F","name":"minor seventh flat five","notes":"F Ab B Eb","symbols":["m7b5","ø7"]},
{"root":"F#","name":"minor seventh flat five","notes":"F# A C E","symbols":["m7b5","ø7"]},
{"root":"G","name":"minor seventh flat five","notes":"G Bb Db F","symbols":["m7b5","ø7"]},
{"root":"Ab","name":"minor seventh flat five","notes":"Ab B D Gb","symbols":["m7b5","ø7"]},
{"root":"A","name":"minor seventh flat five","notes":"A C Eb G","symbols":["m7b5","ø7"]},
{"root":"Bb","name":"minor seventh flat five","notes":"Bb Db E Ab","symbols":["m7b5","ø7"]},
{"root":"B","name":"minor seventh flat five","notes":"B D F A","symbols":["m7b5","ø7"]},
{"root":"C","name":"seventh suspended fourth","notes":"C F G Bb","symbols":["7sus4","7sus"]},
{"root":"C#","name":"seventh suspended fourth","notes":"C# F# G# B","symbols":["7sus4","7sus"]},
{"root":"D","name":"seventh suspended fourth","notes":"D G A C","symbols":["7sus4","7sus"]},
{"root":"Eb","name":"seventh suspended fourth","notes":"Eb Ab Bb Db","symbols":["7sus4","7sus"]},
{"root":"E","name":"seventh suspended fourth","notes":"E A B D","symbols":["7sus4","7sus"]},
{"root":"F","name":"seventh suspended fourth","notes":"F Bb C Eb","symbols":["7sus4","7sus"]},
{"root":"F#","name":"seventh suspended fourth","notes":"F# B C# E","symbols":["7sus4","7sus"]},
{"root":"G","name":"seventh suspended fourth","notes":"G C D F","symbols":["7sus4","7sus"]},
{"root":"Ab","name":"seventh suspended fourth","notes":"Ab Db Eb Gb","symbols":["7sus4","7sus"]},
{"root":"A","name":"seventh suspended fourth","notes":"A D E G","symbols":["7sus4","7sus"]},
{"root":"Bb","name":"seventh suspended fourth","notes":"Bb Eb F Ab","symbols":["7sus4","7sus"]},
{"root":"B","name":"seventh suspended fourth","notes":"B E F# A","symbols":["7sus4","7sus"]},
{"root":"C","name":"ninth","notes":"C E G Bb D","symbols":["9","add9"]},
{"root":"C#","name":"ninth","notes":"C# F G# B D#","symbols":["9","add9"]},
{"root":"D","name":"ninth","notes":"D F# A C E","symbols":["9","add9"]},
{"root":"Eb","name":"ninth","notes":"Eb G Bb Db F","symbols":["9","add9"]},
{"root":"E","name":"ninth","notes":"E G# B D F#","symbols":["9","add9"]},
{"root":"F","name":"ninth","notes":"F A C Eb G","symbols":["9","add9"]},
{"root":"F#","name":"ninth","notes":"F# A# C# E G#","symbols":["9","add9"]},
{"root":"G","name":"ninth","notes":"G B D F A","symbols":["9","add9"]},
{"root":"Ab","name":"ninth","notes":"Ab C Eb Gb Bb","symbols":["9","add9"]},
{"root":"A","name":"ninth","notes":"A C# E G B","symbols":["9","add9"]},
{"root":"Bb","name":"ninth","notes":"Bb D F Ab C","symbols":["9","add9"]},
{"root":"B","name":"ninth","notes":"B D# F# A C#","symbols":["9","add9"]},
{"root":"C","name":"minor ninth","notes":"C Eb G Bb D","symbols":["m9", " minor 9"]},
{"root":"C#","name":"minor ninth","notes":"C# E G# B D#","symbols":["m9", " minor 9"]},
{"root":"D","name":"minor ninth","notes":"D F A C E","symbols":["m9", " minor 9"]},
{"root":"Eb","name":"minor ninth","notes":"Eb Gb Bb Db F","symbols":["m9", " minor 9"]},
{"root":"E","name":"minor ninth","notes":"E G B D F#","symbols":["m9", " minor 9"]},
{"root":"F","name":"minor ninth","notes":"F Ab C Eb G","symbols":["m9", " minor 9"]},
{"root":"F#","name":"minor ninth","notes":"F# A C# E G#","symbols":["m9", " minor 9"]},
{"root":"G","name":"minor ninth","notes":"G Bb D F A","symbols":["m9", " minor 9"]},
{"root":"Ab","name":"minor ninth","notes":"Ab B Eb Gb Bb","symbols":["m9", " minor 9"]},
{"root":"A","name":"minor ninth","notes":"A C E G B","symbols":["m9", " minor 9"]},
{"root":"Bb","name":"minor ninth","notes":"Bb Db F Ab C","symbols":["m9", " minor 9"]},
{"root":"B","name":"minor ninth","notes":"B D F# A C#","symbols":["m9", " minor 9"]},
{"root":"C","name":"major ninth","notes":"C E G B D","symbols":["M9" , "maj9"]},
{"root":"C#","name":"major ninth","notes":"C# F G# C D#","symbols":["M9" , "maj9"]},
{"root":"D","name":"major ninth","notes":"D F# A C# E","symbols":["M9" , "maj9"]},
{"root":"Eb","name":"major ninth","notes":"Eb G Bb D F","symbols":["M9" , "maj9"]},
{"root":"E","name":"major ninth","notes":"E G# B D# F#","symbols":["M9" , "maj9"]},
{"root":"F","name":"major ninth","notes":"F A C E G","symbols":["M9" , "maj9"]},
{"root":"F#","name":"major ninth","notes":"F# A# C# F G#","symbols":["M9" , "maj9"]},
{"root":"G","name":"major ninth","notes":"G B D F# A","symbols":["M9" , "maj9"]},
{"root":"Ab","name":"major ninth","notes":"Ab C Eb G Bb","symbols":["M9" , "maj9"]},
{"root":"A","name":"major ninth","notes":"A C# E G# B","symbols":["M9" , "maj9"]},
{"root":"Bb","name":"major ninth","notes":"Bb D F A C","symbols":["M9" , "maj9"]},
{"root":"B","name":"major ninth","notes":"B D# F# A# C#","symbols":["M9" , "maj9"]},
{"root":"C","name":"ninth augmented fifth","notes":"C E G# Bb D","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"C#","name":"ninth augmented fifth","notes":"C# F A B D#","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"D","name":"ninth augmented fifth","notes":"D F# A# C E","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"Eb","name":"ninth augmented fifth","notes":"Eb G B Db F","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"E","name":"ninth augmented fifth","notes":"E G# C D F#","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"F","name":"ninth augmented fifth","notes":"F A C# Eb G","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"F#","name":"ninth augmented fifth","notes":"F# A# D E G#","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"G","name":"ninth augmented fifth","notes":"G B D# F A","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"Ab","name":"ninth augmented fifth","notes":"Ab C E Gb Bb","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"A","name":"ninth augmented fifth","notes":"A C# F G B","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"Bb","name":"ninth augmented fifth","notes":"Bb D F# Ab C","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"B","name":"ninth augmented fifth","notes":"B D# G A C#","symbols":["7+5" ,"7#5", "7aug5" ]},
{"root":"C","name":"ninth flatted fifth","notes":"C E Gb Bb D","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"C#","name":"ninth flatted fifth","notes":"C# F G B D#","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"D","name":"ninth flatted fifth","notes":"D F# Ab C E","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"Eb","name":"ninth flatted fifth","notes":"Eb G A Db F","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"E","name":"ninth flatted fifth","notes":"E G# Bb D F#","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"F","name":"ninth flatted fifth","notes":"F A B Eb G","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"F#","name":"ninth flatted fifth","notes":"F# A# C E G#","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"G","name":"ninth flatted fifth","notes":"G B Db F A","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"Ab","name":"ninth flatted fifth","notes":"Ab C D Gb Bb","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"A","name":"ninth flatted fifth","notes":"A C# Eb G B","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"Bb","name":"ninth flatted fifth","notes":"Bb D E Ab C","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"B","name":"ninth flatted fifth","notes":"B D# F A C#","symbols":["9b5" , "9-5" , "M9b5", "M9-5"]},
{"root":"C","name":"seventh flat ninth","notes":"C E G Bb Db","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"C#","name":"seventh flat ninth","notes":"C# F G# B D","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"D","name":"seventh flat ninth","notes":"D F# A C Eb","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"Eb","name":"seventh flat ninth","notes":"Eb G Bb Db E","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"E","name":"seventh flat ninth","notes":"E G# B D F","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"F","name":"seventh flat ninth","notes":"F A C Eb Gb","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"F#","name":"seventh flat ninth","notes":"F# A# C# E G","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"G","name":"seventh flat ninth","notes":"G B D F Ab","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"Ab","name":"seventh flat ninth","notes":"Ab C Eb Gb Bbb","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"A","name":"seventh flat ninth","notes":"A C# E G Bb","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"Bb","name":"seventh flat ninth","notes":"Bb D F Ab B","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"B","name":"seventh flat ninth","notes":"B D# F# A C","symbols":["9+" ,"7(9+)", "M9+" ,"M7(9+)"]},
{"root":"C","name":"seventh sharp ninth","notes":"C E G Bb D#","symbols":["7#9" ,"7♯9"]},
{"root":"C#","name":"seventh sharp ninth","notes":"C# F G# B E","symbols":["7#9" ,"7♯9"]},
{"root":"D","name":"seventh sharp ninth","notes":"D F# A C F","symbols":["7#9" ,"7♯9"]},
{"root":"Eb","name":"seventh sharp ninth","notes":"Eb G Bb Db F#","symbols":["7#9" ,"7♯9"]},
{"root":"E","name":"seventh sharp ninth","notes":"E G# B D G","symbols":["7#9" ,"7♯9"]},
{"root":"F","name":"seventh sharp ninth","notes":"F A C Eb G#","symbols":["7#9" ,"7♯9"]},
{"root":"F#","name":"seventh sharp ninth","notes":"F# A# C# E A","symbols":["7#9" ,"7♯9"]},
{"root":"G","name":"seventh sharp ninth","notes":"G B D F A#","symbols":["7#9" ,"7♯9"]},
{"root":"Ab","name":"seventh sharp ninth","notes":"Ab C Eb Gb B","symbols":["7#9" ,"7♯9"]},
{"root":"A","name":"seventh sharp ninth","notes":"A C# E G C","symbols":["7#9" ,"7♯9"]},
{"root":"Bb","name":"seventh sharp ninth","notes":"Bb D F Ab C#","symbols":["7#9" ,"7♯9"]},
{"root":"B","name":"seventh sharp ninth","notes":"B D# F# A D","symbols":["7#9" ,"7♯9"]},
{"root":"C","name":"6 add 9","notes":"C E G A D","symbols":[]},
{"root":"C#","name":"6 add 9","notes":"C# F G# A# D#","symbols":[]},
{"root":"D","name":"6 add 9","notes":"D F# A B E","symbols":[]},
{"root":"Eb","name":"6 add 9","notes":"Eb G Bb C F","symbols":[]},
{"root":"E","name":"6 add 9","notes":"E G# B C# F#","symbols":[]},
{"root":"F","name":"6 add 9","notes":"F A C D G","symbols":[]},
{"root":"F#","name":"6 add 9","notes":"F# A# C# D# G#","symbols":[]},
{"root":"G","name":"6 add 9","notes":"G B D E A","symbols":[]},
{"root":"Ab","name":"6 add 9","notes":"Ab C Eb F Bb","symbols":[]},
{"root":"A","name":"6 add 9","notes":"A C# E F# B","symbols":[]},
{"root":"Bb","name":"6 add 9","notes":"Bb D F G C","symbols":[]},
{"root":"B","name":"6 add 9","notes":"B D# F# G# C#","symbols":[]},
{"root":"C","name":"eleventh","notes":"C E G Bb D F","symbols":[]},
{"root":"C#","name":"eleventh","notes":"C# F G# B D# F#","symbols":[]},
{"root":"D","name":"eleventh","notes":"D F# A C E G","symbols":[]},
{"root":"Eb","name":"eleventh","notes":"Eb G Bb Db F Ab","symbols":[]},
{"root":"E","name":"eleventh","notes":"E G# B D F# A","symbols":[]},
{"root":"F","name":"eleventh","notes":"F A C Eb G Bb","symbols":[]},
{"root":"F#","name":"eleventh","notes":"F# A# C# E G# B","symbols":[]},
{"root":"G","name":"eleventh","notes":"G B D F A C","symbols":[]},
{"root":"Ab","name":"eleventh","notes":"Ab C Eb Gb Bb Db","symbols":[]},
{"root":"A","name":"eleventh","notes":"A C# E G B D","symbols":[]},
{"root":"Bb","name":"eleventh","notes":"Bb D F Ab C Eb","symbols":[]},
{"root":"B","name":"eleventh","notes":"B D# F# A C# E","symbols":[]},
{"root":"C","name":"augmented eleventh","notes":"C E G Bb D F#","symbols":[]},
{"root":"C#","name":"augmented eleventh","notes":"C# F G# B D# G","symbols":[]},
{"root":"D","name":"augmented eleventh","notes":"D F# A C E G#","symbols":[]},
{"root":"Eb","name":"augmented eleventh","notes":"Eb G Bb Db F A","symbols":[]},
{"root":"E","name":"augmented eleventh","notes":"E G# B D F# A#","symbols":[]},
{"root":"F","name":"augmented eleventh","notes":"F A C Eb G B","symbols":[]},
{"root":"F#","name":"augmented eleventh","notes":"F# A# C# E G# C","symbols":[]},
{"root":"G","name":"augmented eleventh","notes":"G B D F A C#","symbols":[]},
{"root":"Ab","name":"augmented eleventh","notes":"Ab C Eb Gb Bb D","symbols":[]},
{"root":"A","name":"augmented eleventh","notes":"A C# E G B D#","symbols":[]},
{"root":"Bb","name":"augmented eleventh","notes":"Bb D F Ab C E","symbols":[]},
{"root":"B","name":"augmented eleventh","notes":"B D# F# A C# F","symbols":[]},
{"root":"C","name":"thirteenth","notes":"C E G Bb D F A","symbols":[]},
{"root":"C#","name":"thirteenth","notes":"C# F G# B D# F# A#","symbols":[]},
{"root":"D","name":"thirteenth","notes":"D F# A C E G B","symbols":[]},
{"root":"Eb","name":"thirteenth","notes":"Eb G Bb Db F Ab C","symbols":[]},
{"root":"E","name":"thirteenth","notes":"E G# B D F# A C#","symbols":[]},
{"root":"F","name":"thirteenth","notes":"F A C Eb G Bb D","symbols":[]},
{"root":"F#","name":"thirteenth","notes":"F# A# C# E G# B D#","symbols":[]},
{"root":"G","name":"thirteenth","notes":"G B D F A C E","symbols":[]},
{"root":"Ab","name":"thirteenth","notes":"Ab C Eb Gb Bb Db F","symbols":[]},
{"root":"A","name":"thirteenth","notes":"A C# E G B D F#","symbols":[]},
{"root":"Bb","name":"thirteenth","notes":"Bb D F Ab C Eb G","symbols":[]},
{"root":"B","name":"thirteenth","notes":"B D# F# A C# E G#","symbols":[]},
{"root":"C","name":"thirteenth flat ninth","notes":"C E G Bb Db F A","symbols":[]},
{"root":"C#","name":"thirteenth flat ninth","notes":"C# F G# B D F# A#","symbols":[]},
{"root":"D","name":"thirteenth flat ninth","notes":"D F# A C Eb G B","symbols":[]},
{"root":"Eb","name":"thirteenth flat ninth","notes":"Eb G Bb Db E Ab C","symbols":[]},
{"root":"E","name":"thirteenth flat ninth","notes":"E G# B D F A C#","symbols":[]},
{"root":"F","name":"thirteenth flat ninth","notes":"F A C Eb Gb Bb D","symbols":[]},
{"root":"F#","name":"thirteenth flat ninth","notes":"F# A# C# E G B D#","symbols":[]},
{"root":"G","name":"thirteenth flat ninth","notes":"G B D F Ab C E","symbols":[]},
{"root":"Ab","name":"thirteenth flat ninth","notes":"Ab C Eb Gb A Db F","symbols":[]},
{"root":"A","name":"thirteenth flat ninth","notes":"A C# E G Bb D F#","symbols":[]},
{"root":"Bb","name":"thirteenth flat ninth","notes":"Bb D F Ab B Eb G","symbols":[]},
{"root":"B","name":"thirteenth flat ninth","notes":"B D# F# A C E G#","symbols":[]},
{"root":"C","name":"thirteenth flat ninth flat fifth","notes":"C E Gb Bb Db F A","symbols":[]},
{"root":"C#","name":"thirteenth flat ninth flat fifth","notes":"C# F G B D F# A#","symbols":[]},
{"root":"D","name":"thirteenth flat ninth flat fifth","notes":"D F# Ab C Eb G B","symbols":[]},
{"root":"Eb","name":"thirteenth flat ninth flat fifth","notes":"Eb G A Db E Ab C","symbols":[]},
{"root":"E","name":"thirteenth flat ninth flat fifth","notes":"E G# Bb D F A C#","symbols":[]},
{"root":"F","name":"thirteenth flat ninth flat fifth","notes":"F A B Eb Gb Bb D","symbols":[]},
{"root":"F#","name":"thirteenth flat ninth flat fifth","notes":"F# A# C E G B D#","symbols":[]},
{"root":"G","name":"thirteenth flat ninth flat fifth","notes":"G B Db F Ab C E","symbols":[]},
{"root":"Ab","name":"thirteenth flat ninth flat fifth","notes":"Ab C D Gb A Db F","symbols":[]},
{"root":"A","name":"thirteenth flat ninth flat fifth","notes":"A C# Eb G Bb D F#","symbols":[]},
{"root":"Bb","name":"thirteenth flat ninth flat fifth","notes":"Bb D E Ab B Eb G","symbols":[]},
{"root":"B","name":"thirteenth flat ninth flat fifth","notes":"B D# F A C E G#","symbols":[]},
{"root":"C","name":"half diminished","notes":"C Eb Gb Bb","symbols":[]},
{"root":"C#","name":"half diminished","notes":"C# E G B","symbols":[]},
{"root":"D","name":"half diminished","notes":"D F Ab C","symbols":[]},
{"root":"Eb","name":"half diminished","notes":"Eb Gb A D","symbols":[]},
{"root":"E","name":"half diminished","notes":"E G Bb D","symbols":[]},
{"root":"F","name":"half diminished","notes":"F Ab B Eb","symbols":[]},
{"root":"F#","name":"half diminished","notes":"F# A C E","symbols":[]},
{"root":"G","name":"half diminished","notes":"G Bb Db F","symbols":[]},
{"root":"Ab","name":"half diminished","notes":"Ab B D Gb","symbols":[]},
{"root":"A","name":"half diminished","notes":"A C Eb G","symbols":[]},
{"root":"Bb","name":"half diminished","notes":"Bb Db E Ab","symbols":[]},
{"root":"B","name":"half diminished","notes":"B D F A","symbols":[]}
    ]